{% set name = "jupysql-plugin" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql_plugin-{{ version }}.tar.gz
  sha256: 7085e178898ee012f4d339f5d356432332a5daa9080ec4cdb3064e0ace7894d6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.10.0
    - jupyterlab >=4.0.0
    - hatch-nodejs-version
    - hatch-jupyter-builder>=0.5
  run:
    - python
    - ploomber-core
    - jupysql

# sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:duckdb
{% set deselect_tests = " --deselect=tests/test_connections.py::test_save_connection_to_config_file_and_connect_in_nested_dir[default]" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_connections.py::test_save_connection_to_config_file_and_connect_in_nested_dir[nested]" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_connector_widget.py::test_method_submit_new_connection" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_connector_widget.py::test_method_submit_new_connection_path" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_connector_widget.py::test_method_connect" %}

test:
  source_files:
    - tests
  imports:
    - jupysql_plugin
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - jupyter_server
    - pytest-jupyter
    - ipython
    - ipywidgets

about:
  home: https://github.com/ploomber/jupysql-plugin
  summary: Jupyterlab extension for JupySQL
  description: Jupyterlab extension for JupySQL
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/ploomber/jupysql-plugin
  doc_url: https://github.com/ploomber/jupysql-plugin

extra:
  recipe-maintainers:
    - edublancas
    - neelasha23
